version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: taskdb
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tasknet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - tasknet
    volumes:
      - backend_uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tasknet

volumes:
  postgres_data:
  backend_uploads:

networks:
  tasknet:
    driver: bridge
